# .github/workflows/live-analyzer.yml

name: Run Live Analysis On-Demand

# Этот "экшен" будет запускаться только по команде от нашего "диспетчера"
on:
  repository_dispatch:
    types: [run-live-analysis]

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      # 1. Скачиваем код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Устанавливаем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: npm install

      # 4. Запускаем наш скрипт анализа
      - name: Run Analysis Script
        env:
          # Передаем все секреты из GitHub в наш скрипт
          SUPABASE_URL: ${{ secrets.PROJECT_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SERVICE_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          HH_USER_AGENT: ${{ secrets.HH_USER_AGENT }}
        run: >
          node scripts/run-live-analysis.js 
          --jobId ${{ github.event.client_payload.job_id }} 
          --companyId ${{ github.event.client_payload.company_id }}