name: Run Live Analysis On-Demand

# 1. ИЗМЕНЕНИЕ: Триггер изменен на workflow_dispatch
# Теперь воркфлоу будет запускаться только при прямом вызове через API
# и будет принимать определенные входные данные (inputs).
on:
  workflow_dispatch:
    inputs:
      job_id:
        description: 'ID задачи из базы данных'
        required: true
      company_id:
        description: 'ID компании для анализа'
        required: true

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      # 1. Скачиваем код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Устанавливаем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: npm install

      # 4. Запускаем наш скрипт анализа
      - name: Run Analysis Script
        env:
          # Передаем все секреты из GitHub в наш скрипт
          SUPABASE_URL: ${{ secrets.PROJECT_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SERVICE_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          HH_USER_AGENT: ${{ secrets.HH_USER_AGENT }}
        run: >
          # 2. ИЗМЕНЕНИЕ: Способ получения параметров
          # Вместо client_payload используем inputs, как того требует workflow_dispatch.
          node scripts/run-live-analysis.js 
          --jobId ${{ github.event.inputs.job_id }} 
          --companyId ${{ github.event.inputs.company_id }}